apiVersion: v2
name: coredns-externaldns
description: A Helm chart for CoreDNS with external-dns plugin integration
type: application
version: 0.3.2
appVersion: "v0.4.1"
home: https://github.com/ionos-cloud/coredns-externaldns
sources:
  - https://github.com/ionos-cloud/coredns-externaldns
maintainers:
  - name: IONOS Cloud
    url: https://github.com/ionos-cloud
dependencies:
  - name: coredns
    version: 1.45.2
    repository: "https://coredns.github.io/helm"
