apiVersion: v2
name: coredns-externaldns
description: A Helm chart for CoreDNS with external-dns plugin integration
type: application
version: 0.1.7
# The appVersion will be updated automatically by the Helm chart release workflow
appVersion: "v0.1.0"
home: https://github.com/ionos-cloud/coredns-externaldns
sources:
  - https://github.com/ionos-cloud/coredns-externaldns
maintainers:
  - name: IONOS Cloud
    url: https://github.com/ionos-cloud
keywords:
  - dns
  - coredns
  - external-dns
  - kubernetes
  - plugin
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: coredns
      image: ghcr.io/ionos-cloud/coredns-externaldns:v0.1.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/ionos-cloud/coredns-externaldns/tree/main/deploy/charts/coredns-externaldns
    - name: Plugin Documentation
      url: https://github.com/ionos-cloud/coredns-externaldns/blob/main/README.md
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
dependencies:
  - name: coredns
    version: "1.43.3"
    repository: "https://coredns.github.io/helm"
